version: '3.8'

services:
  api:
    build: .
    container_name: api_aranceles
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    command: uvicorn main:app --reload --host 0.0.0.0 --port 8000
